#!/bin/bash

set -e

YELLOw='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

main (){
  install_homebrew
  install_profile
  install_git
  install_node
  install_ruby
  install_go
  install_python
  install_apps

  installing "Finished!"
}

install_homebrew() {
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
}

install_profile() {
  installing "Homeshick"
  brew install homeshick
  homeshick clone -f -b danmconrad/profile
  homeshick link profile

  touch ~/.bash_profile

  if grep -q ".conrad-profile" "$HOME/.bash_profile"; then
    log "Bash Profile already sources .conrad-profile"
  else
    log "Sourcing .conrad-profile in .bash_profile"
    printf '\nsource "$HOME/.conrad-profile"' >> $HOME/.bash_profile
  fi
}

install_git() {
  installing "Git"
  brew install git
}

install_node() {
  installing "Node"
  brew install nvm

  export NVM_DIR="$HOME/.nvm"
  source "$(brew --prefix)/opt/nvm/nvm.sh"

  nvm install lts/carbon
  nvm alias default lts/carbon
}

install_ruby() {
  installing "Ruby"
  brew install rbenv
  eval "$(rbenv init -)"
  rbenv install 2.5.1
  rbenv global 2.5.1
}

install_go() {
  installing "Go"
  brew install go
}

install_python() {
  installing "Python"
  brew install pyenv
  eval "$(pyenv init -)"
  pyenv install 3.7.0
  pyenv global 3.7.0
}

install_apps() {
  installing "CLI Apps"
  brew install nmap
  
  installing "Vim"
  brew install vim

  installing "Chrome"
  brew cask install google-chrome

  installing "Docker"
  brew cask install docker

  installing "VSCode"
  brew cask install visual-studio-code

  installing "Spectacle"
  brew cask install spectacle

  installing "iTerm"
  brew cask install iterm2
  
  installing "Slack"
  brew cask install slack
}

installing() {
  printf "${YELLOw}[PROFILE]${NC} $1\n"
}

log() {
  printf "${BLUE}[PROFILE]${NC} $1\n"
}

main
