#!/bin/bash

# set -e

YELLOw='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

main (){
  set_macos_defaults

  install_homebrew
  install_profile
  install_git

  # Languages
  install_python
  install_node
  install_ruby
  install go

  # Utilities
  install nmap
  install vim

  # Apps
  install_cask google-chrome
  install_cask docker
  install_cask slack
  install_cask signal
  install_cask spotify
  install_cask tableplus
  install_cask dashlane
  install_cask balenaetcher
  install_cask imageoptim
  install_cask licecap

  # Apps with config
  install_code
  install_iterm2
  install_spectacle

  installing "Finished!"
}

set_macos_defaults() {
  defaults write com.apple.screencapture location ~/Downloads
  defaults write com.apple.screencapture show-thumbnail -bool FALSE
  defaults write com.apple.dock mru-spaces -bool FALSE
}

install_homebrew() {
  if hash brew 2>/dev/null; then
    return
  fi

  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
}

install_profile() {
  install homeshick

  rm -rf ~/.homesick/repos/profile

  homeshick clone -f -b danmconrad/profile
  homeshick link profile

  touch ~/.bash_profile

  if grep -q ".conrad-profile" "$HOME/.bash_profile"; then
    log "Bash Profile already sources .conrad-profile"
  else
    log "Sourcing .conrad-profile in .bash_profile"
    printf '\nsource "$HOME/.conrad-profile"' >> $HOME/.bash_profile
  fi
}

install_git() {
  install git
  git config --global user.name "Daniel Conrad"
  git config --global user.email daniel.m.conrad@gmail.com
}

install_node() {
  install nvm
  mkdir -p ~/.nvm
  export NVM_DIR="$HOME/.nvm"
  [ -s "$(brew --prefix)/opt/nvm/nvm.sh" ] && . "$(brew --prefix)/opt/nvm/nvm.sh"
  nvm install 11
  nvm alias default 11
}

install_ruby() {
  install rbenv
  rbenv install -f 2.6.2
  rbenv global 2.6.2
}

install_python() {
  install zlib
  export LDFLAGS="-L$(brew --prefix)/opt/zlib/lib"
  export CPPFLAGS="-I$(brew --prefix)/opt/zlib/include"

  install pyenv
  pyenv install -f 3.7.0
  pyenv global 3.7.0
}

install_code() {
  install_cask visual-studio-code
  yes | cp -rf ~/.homesick/repos/profile/configs/code/settings.json ~/Library/Application\ Support/Code/User/settings.json
}

install_spectacle() {
  install_cask spectacle
  mkdir -p ~/Library/Application\ Support/Spectacle/
  yes | cp -rf ~/.homesick/repos/profile/configs/spectacle/Shortcuts.json ~/Library/Application\ Support/Spectacle/Shortcuts.json
}

install_iterm2() {
  install_cask iterm2
  yes | cp -rf ~/.homesick/repos/profile/configs/iterm2/com.googlecode.iterm2.plist ~/Library/Preferences/com.googlecode.iterm2.plist
}

install() {
  installing $1
  brew uninstall $1 || echo "$1 uninstalled"
  brew install -f $1
}

install_cask() {
  installing $1
  brew cask uninstall $1 || echo "$1 uninstalled"
  brew cask install -f $1
}

installing() {
  echo
  echo "================================================="
  printf "${YELLOw}[PROFILE]${NC} $1\n"
  echo "================================================="
  echo
}

log() {
  printf "${BLUE}[PROFILE]${NC} $1\n"
}

main
