#!/bin/bash

set -e

YELLOw='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

main (){
  install_homebrew
  install_profile
  install_node
  install_ruby
  install_python
  
  install go
  install git
  install nmap
  install vim
  install_cask google-chrome
  install_cask docker
  install_cask visual-studio-code
  install_cask spectacle
  install_cask iterm2
  install_cask slack

  installing "Finished!"
}

install_homebrew() {
  if hash brew 2>/dev/null; then
    return 
  fi
  
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
}

install_profile() {
  install homeshick
  
  rm -rf ~/.homesick/repos/profile
  
  homeshick clone -f -b danmconrad/profile
  homeshick link profile

  touch ~/.bash_profile

  if grep -q ".conrad-profile" "$HOME/.bash_profile"; then
    log "Bash Profile already sources .conrad-profile"
  else
    log "Sourcing .conrad-profile in .bash_profile"
    printf '\nsource "$HOME/.conrad-profile"' >> $HOME/.bash_profile
  fi
}

install_node() {
  install nvm  
  nvm install 11
  nvm alias default 11
}

install_ruby() {
  install rbenv
  rbenv install 2.6.2
  rbenv global 2.6.2
}

install_python() {
  install pyenv
  pyenv install 3.7.0
  pyenv global 3.7.0
}

install() {
  installing $1
  brew uninstall $1 || echo "$1 uninstalled"
  brew install -f $1
}

install_cask() {
  installing $1
  brew cask uninstall $1 || echo "$1 uninstalled"
  brew cask install -f $1
}

installing() {
  echo "\n================================================="
  printf "${YELLOw}[PROFILE]${NC} $1\n"
  echo "=================================================\n"
}

log() {
  printf "${BLUE}[PROFILE]${NC} $1\n"
}

main
