#!/bin/bash

main (){
  install_homebrew
  install_git
  install_node
  install_ruby
  install_go
  install_profile
  install_apps
}

install_homebrew() {
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
}

install_git() {
  brew install git
}

install_node() {
  brew install nvm

  export NVM_DIR="$HOME/.nvm"
  . "/usr/local/opt/nvm/nvm.sh"

  nvm install 6
  nvm alias default 6
}

install_ruby() {
  brew install rbenv ruby-build

  eval "$(rbenv init -)"

  rbenv install 2.4.0
  rbenv global 2.4.0
  gem install bundler foreman homesick --no-ri --no-rdoc
}

install_go() {
  brew install go
}

install_profile() {
  touch ~/.bash_profile
  homesick clone -f git@github.com:danmconrad/profile.git
  homesick link profile
}

install_apps() {
  brew install Caskroom/cask/google-chrome
  brew install caskroom/cask/visual-studio-code
  brew install Caskroom/cask/spectacle
  brew install Caskroom/cask/iterm2
}

main
