#!/bin/bash

function main (){
  touch ~/.bash_profile
  
  install_homebrew
  install_git
  install_node
  install_ruby
  install_profile
}

function install_homebrew() {
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
}

function install_git() {
  brew install git
}

function install_node() {
  brew install nvm
  
  export NVM_DIR="$HOME/.nvm"
  . "/usr/local/opt/nvm/nvm.sh"
  
  nvm install 6
  nvm alias default 6
}

function install_ruby() {
  brew install rbenv ruby-build
  
  eval "$(rbenv init -)"
  
  rbenv install 2.4.0
  rbenv global 2.4.0
  gem install bundler foreman gemfury gem-release git_remote_branch git-smart httparty homesick papertrail pry terminal-table travis --no-ri --no-rdoc
}

function install_profile() {
  homesick clone -f git@github.com:danmconrad/profile.git
  homesick link profile
}

main
